server.port=8000
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.retry.instances.inventoryRetry.maxAttempts=3
resilience4j.retry.instances.inventoryRetry.waitDuration=2s
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orderdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
