events {
  worker_connections 1024;
}

http {
  # (MỚI) Định nghĩa vùng nhớ cho Rate Limiting.
  # 10m RAM để lưu trữ IP. Giới hạn tốc độ: 5 request/giây cho mỗi IP.
  limit_req_zone $binary_remote_addr zone=my_rate_limit:10m rate=5r/s;

  # Định nghĩa nơi lưu trữ bộ nhớ đệm (Cache) trên ổ cứng của Nginx
  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_api_cache:10m max_size=100m inactive=60m use_temp_path=off;

  # Định nghĩa cụm backend
  upstream backend_cluster {
    # Đổi thành 'least_conn;' để thử thuật toán khác
    # Đổi thành 'ip_hash;' để test Sticky Session
    # ip_hash;
    server web_s1:8000 max_fails=3 fail_timeout=30s;
    server web_s2:8000 max_fails=3 fail_timeout=30s;
  }

  # Server 1: Hứng cổng 80 (HTTP) và đá tất cả sang cổng 443 (HTTPS)
  server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
  }
  # Server 2: Hứng cổng 443 (HTTPS) và xử lý chính
  server {
    listen 443 ssl;
    server_name localhost;
    # Khai báo đường dẫn tới chứng chỉ
    ssl_certificate /etc/nginx/nginx.crt;
    ssl_certificate_key /etc/nginx/nginx.key;
    location /api {
      limit_req zone=my_rate_limit;
      proxy_cache my_api_cache;
      proxy_cache_valid 200 5s;
      add_header X-Cache-Status $upstream_cache_status;
      proxy_pass http://backend_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_connect_timeout 5s;
      proxy_read_timeout 10s;
    }
    location /health {
      proxy_pass http://backend_cluster;
    }
  }
}
